"""
Winner Recommender Dashboard
Run with: streamlit run app.py
"""

import sqlite3
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent
DB_PATH = ROOT / "data" / "db" / "winner.db"
sys.path.insert(0, str(ROOT / "src"))

from recommend.send_weekly import generate_picks as _generate_picks

@st.cache_data(ttl=3600, show_spinner=False)
def generate_picks():
    return _generate_picks()

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Winner Recommender",
    page_icon="⚽",
    layout="wide",
)

# ── Clean minimal styling ─────────────────────────────────────────────────────
st.markdown("""
<style>
    .block-container { padding-top: 2rem; padding-bottom: 2rem; }
    h1 { font-size: 1.6rem; font-weight: 700; letter-spacing: -0.5px; }
    h2 { font-size: 1.2rem; font-weight: 600; }
    h3 { font-size: 1.05rem; font-weight: 600; }
    .slip-box {
        border: 1px solid #e0e0e0;
        border-radius: 8px;
        padding: 1.2rem 1.4rem;
        margin-bottom: 1rem;
        background: #fafafa;
    }
    .leg-row {
        padding: 0.5rem 0;
        border-bottom: 1px solid #efefef;
        font-size: 0.95rem;
    }
    .leg-row:last-child { border-bottom: none; }
    .tag {
        display: inline-block;
        font-size: 0.72rem;
        font-weight: 600;
        padding: 2px 8px;
        border-radius: 4px;
        background: #ececec;
        color: #444;
        margin-right: 6px;
        letter-spacing: 0.3px;
    }
    .stretch-tag { background: #f0f0f0; color: #888; }
    .metric-label { font-size: 0.78rem; color: #888; text-transform: uppercase; letter-spacing: 0.5px; }
    .metric-value { font-size: 1.5rem; font-weight: 700; color: #111; }
    div[data-testid="stMetric"] { background: #f7f7f7; border-radius: 8px; padding: 0.7rem 1rem; }
    div[data-testid="stMetricValue"] { font-size: 1.4rem; }
    .stTabs [data-baseweb="tab"] { font-size: 0.9rem; font-weight: 500; }
    footer { visibility: hidden; }
</style>
""", unsafe_allow_html=True)

st.markdown("## ⚽ Winner Recommender")
st.caption(f"Model v5 · Combined slip (H/A + 1st Corner) · EV 1.68 · 75% win rate over 27 weeks")

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("### Actions")
    if st.button("Refresh odds & picks", use_container_width=True):
        with st.spinner("Fetching latest odds..."):
            venv_py = ROOT / ".venv" / "bin" / "python"
            subprocess.run([str(venv_py), str(ROOT / "src" / "data" / "fetch_odds.py")],
                           cwd=str(ROOT), capture_output=True)
        st.success("Done!")
        st.rerun()

    st.divider()
    st.markdown("**Slip structure**")
    st.markdown("- Slip 1: H/A + 1st Corner")
    st.markdown("- Stretch: optional H/A single + draw")
    st.divider()

    with st.expander("📖 Term glossary"):
        st.markdown("""
**ph / pa / pd**
Pinnacle implied probability for Home win / Away win / Draw. Vig-removed so they sum to 100%. Pinnacle is the sharpest bookmaker — their probabilities are the most accurate signal.

---

**venue_gap**
Home team's points in their last 5 *home* games minus the away team's points in their last 5 *away* games. Measures form specifically at each team's venue. A gap of +5 or more means the home side is significantly stronger on their own ground.

---

**pts5_diff**
Home team's overall points (last 5 games, all venues) minus the away team's overall points. Secondary form signal. Must align with venue_gap for a pick to qualify.

---

**Confidence score**
A weighted score for each pick starting from Pinnacle probability × 10, then multiplied by bonuses: win streak, opponent losing streak, attacking mismatch, form dominance. Higher = stronger pick. The accumulator only fires when the weakest leg is ≥ 13.

---

**streak**
How many consecutive wins the home team has in their home games (for H picks), or consecutive wins the away team has in away games (for A picks). A streak of 3+ gives a 1.25× confidence bonus.

---

**lstreak**
Losing streak of the *opponent*. E.g. if the away team has lost their last 3 away games, that's an lstreak of 3. Gives a 1.15× confidence bonus to the home pick.

---

**trend**
Points in the last 3 games minus points in the 3 games before that. Positive = improving form, negative = declining. A team must have trend ≥ 0 to qualify (no declining teams).

---

**draw rate (dr10)**
Fraction of the last 10 games that ended in a draw, per team. Both teams must be above 20% for a draw pick to qualify. Teams with high draw rates tend to play more cautious, balanced football.

---

**exp_first_home**
Expected fraction of corners generated by the home team. Calculated from each team's rolling 5-game corner averages at their respective venues. Above 65% → pick home 1st corner. Below 35% → pick away.

---

**EV (Expected Value)**
Average return per unit staked over many bets. EV > 1.0 means profitable long-term. E.g. EV 1.68 means for every 100 NIS staked you expect 168 NIS back on average.

---

**📌 vs 📊**
📌 = Pinnacle closing odds used (most accurate, historical data)
📊 = Market average odds used (recent weeks where Pinnacle closing odds not yet published)
""")

    st.divider()
    st.caption("Data: football-data.co.uk + The Odds API")

# ── Tabs ──────────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["This Week", "Past Results", "Match History"])


# ═══════════════════════════════════════════════════════════════════════════════
# TAB 1 — THIS WEEK
# ═══════════════════════════════════════════════════════════════════════════════
with tab1:
    st.markdown(f"### Week of {datetime.today().strftime('%d %B %Y')}")

    with st.spinner("Generating picks..."):
        try:
            best_ha, best_crn, best_draw, all_ha, all_draws = generate_picks()
        except Exception as e:
            st.error(f"Error generating picks: {e}")
            best_ha = best_crn = best_draw = None
            all_ha = all_draws = []

    col_s1, col_stretch = st.columns(2)

    # ── Slip 1 ────────────────────────────────────────────────────────────────
    with col_s1:
        st.markdown("**Slip 1 — Combined**")
        if best_ha:
            combined_odds = round(best_ha['odds'] * (best_crn['odds'] if best_crn else 1), 2)
            st.metric("Combined odds", f"{combined_odds:.2f}×")

            st.markdown(f"""
<div class="slip-box">
  <div class="leg-row">
    <span class="tag">H/A</span> <b>{best_ha['match']}</b><br>
    <small>{best_ha['league']} · {best_ha['kickoff']} · Pick: {'Home' if best_ha['pick']=='H' else 'Away'} @ {best_ha['odds']:.2f}</small>
  </div>
  <div class="leg-row">
    <span class="tag">1st Corner</span> <b>{best_crn['match'] if best_crn else '—'}</b><br>
    <small>{f"{best_crn['league']} · {best_crn['kickoff']} · {'Home' if best_crn['pick']=='H' else 'Away'} @ {best_crn['odds']:.2f}" if best_crn else 'No qualifying pick'}</small>
  </div>
</div>
""", unsafe_allow_html=True)

            with st.expander("Why Leg 1 (H/A)?"):
                st.markdown(f"_{best_ha['why']}_  \nConfidence: **{best_ha['conf']}**")
                # Recent form
                conn = sqlite3.connect(DB_PATH)
                ht_name = best_ha['match'].split(' vs ')[0]
                at_name = best_ha['match'].split(' vs ')[1]
                home_form = pd.read_sql(f"""
                    SELECT date, away_team AS opponent,
                           home_goals || '-' || away_goals AS score, result
                    FROM matches_history WHERE home_team = '{ht_name}'
                    AND result IS NOT NULL ORDER BY date DESC LIMIT 5
                """, conn)
                away_form = pd.read_sql(f"""
                    SELECT date, home_team AS opponent,
                           away_goals || '-' || home_goals AS score, result
                    FROM matches_history WHERE away_team = '{at_name}'
                    AND result IS NOT NULL ORDER BY date DESC LIMIT 5
                """, conn)
                conn.close()
                c1, c2 = st.columns(2)
                with c1:
                    st.caption(f"{ht_name} — last 5 home")
                    home_form['result'] = home_form['result'].map({'H':'W','D':'D','A':'L'})
                    st.dataframe(home_form, hide_index=True, use_container_width=True)
                with c2:
                    st.caption(f"{at_name} — last 5 away")
                    away_form['result'] = away_form['result'].map({'H':'L','D':'D','A':'W'})
                    st.dataframe(away_form, hide_index=True, use_container_width=True)

            if best_crn:
                with st.expander("Why Leg 2 (1st Corner)?"):
                    st.markdown(f"_{best_crn['why']}_  \nConfidence: **{best_crn['conf']}**")
        else:
            st.warning("No qualifying H/A pick — skip Slip 1")

    # ── Stretch + Draw ────────────────────────────────────────────────────────
    with col_stretch:
        st.markdown("**Stretch — Optional**")
        st.caption("Lower-conviction picks — bet smaller or skip.")

        if len(all_ha) > 1:
            stretch = all_ha[1]
            st.markdown(f"""
<div class="slip-box">
  <div class="leg-row">
    <span class="tag stretch-tag">H/A</span> <b>{stretch['match']}</b><br>
    <small>{stretch['league']} · {stretch['kickoff']} · {'Home' if stretch['pick']=='H' else 'Away'} @ {stretch['odds']:.2f}</small>
  </div>
</div>
""", unsafe_allow_html=True)
            with st.expander("Why this H/A pick?"):
                st.markdown(f"_{stretch['why']}_  \nConfidence: **{stretch['conf']}** _(lower than primary)_")

        if best_draw:
            st.markdown(f"""
<div class="slip-box">
  <div class="leg-row">
    <span class="tag stretch-tag">Draw</span> <b>{best_draw['match']}</b><br>
    <small>{best_draw['league']} · {best_draw['kickoff']} · Draw @ {best_draw['odds']:.2f}</small>
  </div>
</div>
""", unsafe_allow_html=True)
            with st.expander("Why this draw?"):
                st.markdown(f"_{best_draw['why']}_  \nConfidence: **{best_draw['conf']}**")

        if len(all_ha) <= 1 and not best_draw:
            st.info("No stretch candidates this week.")


# ═══════════════════════════════════════════════════════════════════════════════
# TAB 2 — PAST RESULTS
# ═══════════════════════════════════════════════════════════════════════════════
with tab2:
    st.markdown("### Past Results — Current Season")

    csv_path = ROOT / "data" / "reports" / "combined_slip_last20.csv"
    if not csv_path.exists():
        st.warning("No past results file found. Run the backtest first.")
    else:
        df = pd.read_csv(csv_path)

        # Add/replace this week as pending (replace if it exists but has no picks)
        current_week_label = str(pd.Timestamp.today().to_period('W'))
        already_has_picks = (
            df['week'].eq(current_week_label) & df['n_legs'].fillna(0).gt(0)
        ).any()
        if best_ha and not already_has_picks:
            df = df[df['week'] != current_week_label]  # drop the empty row if it exists
            combined_odds = round(best_ha['odds'] * (best_crn['odds'] if best_crn else 1), 2)
            pending_legs = f"{best_ha['match']} ({('Home' if best_ha['pick']=='H' else 'Away')})"
            if best_crn:
                pending_legs += f" + {best_crn['match']} (1st crn {best_crn['pick']})"
            pending_row = {
                'week': current_week_label,
                'odds_source': 'pinnacle',
                'slip_won': None,
                'combined_odds': combined_odds,
                'n_legs': 2 if best_crn else 1,
                'leg1_market': 'H/A', 'leg1_match': best_ha['match'],
                'leg1_pick': best_ha['pick'], 'leg1_odds': best_ha['odds'],
                'leg1_why': best_ha['why'], 'leg1_hit': None,
                'leg2_market': '1st CRN' if best_crn else '',
                'leg2_match': best_crn['match'] if best_crn else '',
                'leg2_pick': best_crn['pick'] if best_crn else '',
                'leg2_odds': best_crn['odds'] if best_crn else '',
                'leg2_why': best_crn['why'] if best_crn else '',
                'leg2_hit': None,
                'leg3_market': '', 'leg3_match': '', 'leg3_pick': '',
                'leg3_odds': '', 'leg3_why': '', 'leg3_hit': '',
                'draw_match': best_draw['match'] if best_draw else '',
                'draw_pick': 'D' if best_draw else '',
                'draw_odds': best_draw['odds'] if best_draw else '',
                'draw_hit': None,
            }
            df = pd.concat([df, pd.DataFrame([pending_row])], ignore_index=True)

        # Summary metrics
        has_result = df[df['slip_won'].notna() & (df['slip_won'] != '')]
        wins = (has_result['slip_won'] == True).sum()
        total = len(has_result)
        avg_odds = has_result['combined_odds'].dropna().mean()
        draw_df = df[df['draw_hit'].notna() & (df['draw_hit'] != '')]
        draw_wins = (draw_df['draw_hit'] == True).sum()

        c1, c2, c3, c4, c5 = st.columns(5)
        c1.metric("Weeks played", total)
        c2.metric("Slip win rate", f"{wins/total:.0%}" if total else "—")
        c3.metric("Avg odds", f"{avg_odds:.2f}×" if avg_odds else "—")
        c4.metric("EV", f"{(wins/total)*avg_odds:.2f}" if total and avg_odds else "—")
        c5.metric("Draw accuracy", f"{draw_wins/len(draw_df):.0%}" if len(draw_df) else "—")

        st.markdown("#### P&L Calculator")
        stake = st.slider("Stake per week (NIS)", 10, 500, 50, step=10)

        balance = 0
        pnl_rows = []
        for _, r in df.iterrows():
            won = r.get('slip_won')
            if won is None or won == '':
                pnl_rows.append({
                    'week': str(r['week'])[:22],
                    'src': '📌' if r.get('odds_source') == 'pinnacle' else '📊',
                    'result': '⏳ Pending',
                    'odds': r['combined_odds'],
                    'P&L (NIS)': '—',
                    'Balance (NIS)': f"+{balance}" if balance >= 0 else str(balance),
                })
                continue
            if won is True or won == True:
                profit = round(stake * r['combined_odds'] - stake, 1)
            else:
                profit = -stake
            balance += profit
            pnl_rows.append({
                'week': str(r['week'])[:22],
                'src': '📌' if r.get('odds_source') == 'pinnacle' else '📊',
                'result': '✅ Won' if profit > 0 else '❌ Lost',
                'odds': r['combined_odds'],
                'P&L (NIS)': f"+{profit}" if profit > 0 else str(profit),
                'Balance (NIS)': f"+{balance}" if balance >= 0 else str(balance),
            })

        pnl_df = pd.DataFrame(pnl_rows).iloc[::-1].reset_index(drop=True)

        col_a, col_b = st.columns([3.9, 1])
        with col_a:
            st.dataframe(pnl_df, hide_index=True, use_container_width=True,
                         height=min(40 + len(pnl_df) * 35, 950))
        with col_b:
            st.metric("Total staked", f"{total * stake} NIS")
            st.metric("Net profit",
                      f"{'+' if balance >= 0 else ''}{balance} NIS",
                      delta=f"{balance/(total*stake)*100:.1f}% ROI" if total else None)

        st.divider()
        st.markdown("#### Drill into a week")
        all_weeks = df['week'].tolist()[::-1]
        selected = st.selectbox("Select week", all_weeks, index=0)
        row = df[df['week'] == selected].iloc[0]

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("**Combined Slip**")
            for i in range(1, 4):
                mkt = row.get(f'leg{i}_market', '')
                if not mkt:
                    break
                hit = row.get(f'leg{i}_hit')
                icon = '✅' if hit is True else ('❌' if hit is False else '⏳')
                st.markdown(
                    f"{icon} **[{mkt}]** {row[f'leg{i}_match']} — "
                    f"**{row[f'leg{i}_pick']}** @ {row[f'leg{i}_odds']}×  \n"
                    f"  <small>{row[f'leg{i}_why']}</small>",
                    unsafe_allow_html=True
                )
            won = row.get('slip_won')
            label = '✅ WON' if won is True else ('❌ LOST' if won is False else '⏳ Pending')
            st.markdown(f"**Result: {label} @ {row['combined_odds']}×**")

        with col2:
            st.markdown("**Draw Single**")
            if row.get('draw_match'):
                dhit = row.get('draw_hit')
                icon = '✅' if dhit is True else ('❌' if dhit is False else '⏳')
                st.markdown(f"{icon} {row['draw_match']} → Draw @ {row['draw_odds']}×")
            else:
                st.markdown("_No draw pick this week_")


# ═══════════════════════════════════════════════════════════════════════════════
# TAB 3 — MATCH HISTORY
# ═══════════════════════════════════════════════════════════════════════════════
with tab3:
    st.markdown("### Match History")

    conn = sqlite3.connect(DB_PATH)
    leagues = ['All'] + pd.read_sql(
        "SELECT DISTINCT league FROM matches_history ORDER BY league", conn
    )['league'].tolist()

    col1, col2, col3 = st.columns(3)
    sel_league = col1.selectbox("League", leagues)
    sel_season = col2.selectbox("Season", ['All', '2025/26', '2024/25', '2023/24', '2022/23'])
    sel_team   = col3.text_input("Search team", "")

    query = """
        SELECT date, league, home_team, away_team,
               home_goals || '-' || away_goals AS score,
               result, ht_result,
               home_corners, away_corners,
               ROUND(pinnacle_prob_h, 2) AS pin_ph,
               ROUND(pinnacle_prob_d, 2) AS pin_pd,
               ROUND(pinnacle_prob_a, 2) AS pin_pa
        FROM matches_history WHERE 1=1
    """
    if sel_league != 'All':
        query += f" AND league = '{sel_league}'"
    if sel_season != 'All':
        year = int(sel_season[:4])
        query += f" AND date >= '{year}-08-01' AND date < '{year+1}-07-01'"
    if sel_team:
        query += f" AND (home_team LIKE '%{sel_team}%' OR away_team LIKE '%{sel_team}%')"
    query += " ORDER BY date DESC LIMIT 300"

    hist = pd.read_sql(query, conn)
    conn.close()

    st.caption(f"{len(hist)} matches shown")
    st.dataframe(hist, hide_index=True, use_container_width=True, height=600)
